"""
MedCollab — Diagnosis Report Models

Final output of the MedCollab pipeline including the consensus result,
causal explanation, and all supporting/dissenting evidence.
"""

from __future__ import annotations
from pydantic import BaseModel, Field
from src.models.ibis import IBISPosition
from src.models.causal_chain import HDCC


class AgentScore(BaseModel):
    """Score assigned to each specialist by the Consensus Agent."""

    agent_name: str
    logic_score: float = Field(description="IBIS logic consistency score")
    evidence_score: float = Field(description="Strength of evidence cited")
    weight: float = Field(description="Final voting weight (normalized)")


class ConsensusResult(BaseModel):
    """Result of the GP-led consensus mechanism."""

    round_number: int = Field(description="Which consensus round produced this")
    consensus_reached: bool = Field(description="Whether threshold was met")
    consensus_score: float = Field(
        ge=0.0, le=1.0, description="Overall agreement level"
    )
    agent_scores: list[AgentScore] = Field(
        default_factory=list, description="Per-agent quality scores"
    )
    primary_diagnosis: str = Field(description="Top diagnosis from weighted vote")
    vote_distribution: dict[str, float] = Field(
        default_factory=dict,
        description="Diagnosis → weighted vote share",
    )


class DiagnosisReport(BaseModel):
    """
    The final output of the MedCollab pipeline.
    Contains everything needed for the paper's evaluation + Streamlit display.
    """

    primary_diagnosis: str = Field(
        ..., description="Final consensus diagnosis"
    )
    differential_diagnoses: list[str] = Field(
        default_factory=list,
        description="Alternative diagnoses considered",
    )
    confidence_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Overall diagnostic confidence",
    )

    # Evidence trail
    causal_chain: HDCC = Field(
        default_factory=HDCC,
        description="Hierarchical Disease Causal Chain",
    )
    specialist_positions: list[IBISPosition] = Field(
        default_factory=list,
        description="All specialist IBIS positions",
    )
    consensus: ConsensusResult | None = Field(
        default=None, description="Consensus voting details"
    )

    # Patient Interaction Agent output (NOVEL)
    follow_up_questions_asked: list[str] = Field(
        default_factory=list,
        description="Questions generated by Patient Interaction Agent",
    )
    follow_up_answers: list[str] = Field(
        default_factory=list,
        description="Answers received from patient / simulated patient",
    )
    evidence_updates: list[str] = Field(
        default_factory=list,
        description="New evidence discovered via follow-up",
    )

    # Clinical recommendations
    recommendations: list[str] = Field(
        default_factory=list,
        description="Recommended next steps, tests, or referrals",
    )
    dissenting_opinions: list[IBISPosition] = Field(
        default_factory=list,
        description="Specialist positions that disagreed with final diagnosis",
    )
